server.port=8080
spring.application.name=manga-backend-services

# D\u00F9ng host Pooler IPv4
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.fkxvnvujmxpmxckxwebp
spring.datasource.password=Kh1227102005@#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true